ListToDo.Web/Models/ListToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ListToDo.Web.Models
{
    public class ListToDo
    {
        public int Id { get; set; }
        public string NomeItem { get; set; }
        public string DescricaoItem { get; set; }
        public string Status { get; set; }
        public DateTime DataDeCriacao { get; set; }
        public DateTime DataConclusao { get; set; }
    }
}

ListToDo.Web/Models/ViewModels/ListaDeItemViewModel.cs
using System.Collections.Generic;

namespace ListToDo.Web.Models.ViewModels
{
    public class ListaDeItemViewModel
    {
        public List<ListToDo> ListToDo_Pendetens { get; set; }
        public List<ListToDo> ListToDo_Concluidas { get; set; }
    }
}

ListToDo.Web/Controllers/ListaToDoController.cs
using ListToDo.Web.Models.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ListToDo.Web.Controllers
{
    public class ListaToDoController : Controller
    {
        ListaDeItemViewModel _model = new ListaDeItemViewModel();
        string BaseUrl = "http://localhost:63078/";
        // GET: ListaToDo

        public async Task<ActionResult> Index()
        {
            List<Models.ListToDo> listToDos = new List<Models.ListToDo>();

            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/ListToDo");

                if (Res.IsSuccessStatusCode)
                {
                    var ListItens = Res.Content.ReadAsStringAsync().Result;
                    listToDos = JsonConvert.DeserializeObject<List<Models.ListToDo>>(ListItens, settings);
                    _model.ListToDo_Pendetens = listToDos.Where(x => x.Status == "Pendente").ToList();
                    _model.ListToDo_Concluidas = listToDos.Where(x => x.Status == "Concluido").ToList();
                }
            }

            return View(_model);
        }
        public ActionResult Finalizar(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = client.GetAsync("api/Finalizar/" + id).Result;
                return RedirectToAction("Index");
            }
        }
        public ActionResult Editar(int id)
        {
            Models.ListToDo listToDo = new Models.ListToDo();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = client.GetAsync("api/ListToDo/" + id).Result;

                if (Res.IsSuccessStatusCode)
                {
                    return View(Res.Content.ReadAsAsync<Models.ListToDo>().Result);
                }
                return View(listToDo);
            }
        }
        public ActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Form(Models.ListToDo listToDo)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res =  client.PostAsJsonAsync("api/ListToDo",listToDo).Result;
                return RedirectToAction("Index");
            }            
        }
        public ActionResult FindOne(int id)
        {
            Models.ListToDo listToDo = new Models.ListToDo();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res =  client.GetAsync("api/ListToDo/"+ id).Result;

                if (Res.IsSuccessStatusCode)
                {
                    return View(Res.Content.ReadAsAsync<Models.ListToDo>().Result);
                }
                return View("Index");
            }
        }

        public ActionResult Update(Models.ListToDo listToDo)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BaseUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage Res = client.PutAsJsonAsync("api/ListToDo/"+listToDo.Id, listToDo).Result;
                }
                return View();
            }
            catch (Exception)
            {

                return View();
            }           
        }

        public ActionResult Delete(int id)
        {
            try
            {
                Models.ListToDo listaToDo = new Models.ListToDo();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BaseUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("Application/json"));
                    HttpResponseMessage Res = client.DeleteAsync("api/ListToDo" + id).Result;
                }
                return View("Index");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }
    }
}

ListToDo.Web/Views/ListaToDo/Editar.cshtml
@model ListToDo.Web.Models.ListToDo
@{
    ViewBag.Title = "Editar";
}

<section class="form-criar-tarefa">
    @using (Html.BeginForm("Update", "ListaToDo", FormMethod.Post, new { @class = "form-horizontal" }))
    {

        <div class="form-group">
            <div class="col-md-4 inputGroupContainer">
                <h2 class="text-center">Criar Nova Tarefa</h2>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label">Nome:</label>
            <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-check"></i></span>
                    @Html.TextBoxFor(f => f.NomeItem, new { @class = "form-control", placeholder = "Nome Item" })
                    @Html.ValidationMessageFor(f => f.NomeItem)
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label">Descrição:</label>
            <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
                    @Html.TextAreaFor(f => f.DescricaoItem, new { @class = "form-control", placeholder = "Descrição do Item" })
                    @Html.ValidationMessageFor(f => f.DescricaoItem)
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary">Salvar <span class="glyphicon glyphicon-floppy-disk"></span></button>
            </div>
        </div>
    }
</section>

ListToDo.Web/Views/ListaToDo/FindOne.cshtml
@model ListToDo.Web.Models.ListToDo
@{
    ViewBag.Title = "FindOne";
}

<section>
    <div class="col-lg-12">
        <div class="col-md-12">
            <label class="col-md-4 control-label">Nome:</label>
            <label class="col-md-4 control-label">@Html.Raw(Model.NomeItem)</label>
        </div>
        <div class="col-md-12">
            <label class="col-md-4 control-label">Descrição:</label>
            <label class="col-md-4 control-label">@Html.Raw(Model.DescricaoItem)</label>
        </div>
        <div class="col-md-12">
            <label class="col-md-4 control-label">Status:</label>
            <label class="col-md-4 control-label">@Html.Raw(Model.Status)</label>
        </div>
        <div class="col-md-12">
            <label class="col-md-4 control-label">Data Criação:</label>
            <label class="col-md-4 control-label">@Html.Raw(Model.DataDeCriacao)</label>
        </div>
        @if (Model.Status == "Pendente")
        {
            <div class="col-md-12">
                <div class="col-md-4">
                    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Deletar", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
                </div>
            </div>
        }


    </div>
</section>

ListToDo.Web/Views/ListaToDo/Form.cshtml
@model ListToDo.Web.Models.ListToDo
@{
    ViewBag.Title = "Form";
}

<section class="form-criar-tarefa">
    @using (Html.BeginForm("Form", "ListaToDo", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.ValidationMessage("Intem Lista Inválido")

        <div class="form-group">
            <div class="col-md-4 inputGroupContainer">
                <h2 class="text-center">Criar Nova Tarefa</h2>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label">Nome:</label>
            <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-check"></i></span>
                    @Html.TextBoxFor(f => f.NomeItem, new { @class = "form-control", placeholder = "Nome Item" })
                    @Html.ValidationMessageFor(f => f.NomeItem)
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label">Descrição:</label>
            <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
                    @Html.TextAreaFor(f => f.DescricaoItem, new { @class = "form-control", placeholder = "Descrição do Item" })
                    @Html.ValidationMessageFor(f => f.DescricaoItem)
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary">Criar Tarefa <span class="glyphicon glyphicon-floppy-disk"></span></button>
            </div>
        </div>
    }
</section>

ListToDo.Web/Views/ListaToDo/Index.cshtml
@model ListToDo.Web.Models.ViewModels.ListaDeItemViewModel
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-lg-12">
        <div class="col-lg-6">
            <h2 class="text-center">Itens Pendentes</h2>
            @if (Model.ListToDo_Pendetens.Count >= 1)
            {
                foreach (var item in Model.ListToDo_Pendetens)
                {
                    <div class="col-lg-3 card-pendente">
                        @Html.ActionLink(item.NomeItem, "FindOne", new { id = item.Id }, new { @class = "" })
                        @Html.ActionLink("Finalizar", "Finalizar", new { id = item.Id }, new { @class = "btn btn-success" })

                    </div>
                }
            }
            else
            {
                <div class="alert alert-danger" role="alert">Não há item Pendente</div>
            }
        </div>

        <div class="col-lg-6">
            <h2 class="text-center">Itens Concluído</h2>
            @if (Model.ListToDo_Concluidas.Count >= 1)
            {
                foreach (var item in Model.ListToDo_Concluidas)
                {
                    <div class="col-lg-3 card-concluido">
                        @Html.ActionLink(item.NomeItem, "FindOne", new { id = item.Id }, new { @class = "" })
                    </div>
                }
            }
            else
            {
                <div class="alert alert-danger" role="alert">Não há item Concluido</div>
            }
        </div>
    </div>
</div>

ListToDo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>